const test=require('node:test'),assert=require('node:assert/strict'),{analyseContract}=require('./riskEngine');
for(const specimen of require('./test-contracts.json'))test(specimen.id,()=>{const r=analyseContract(specimen.text,specimen.id,specimen.jurisdiction);const ids=r.issues.map(x=>x.id.replace(/-\d+$/,'')); for(const expected of specimen.expected) assert.ok(ids.includes(expected), `missing expected ${expected}: ${ids.join(', ')}`);assert.ok(typeof r.exposure==='string' && r.exposure.length>0);assert.ok(r.coverageWarning);});
test('Service cancellation is not an employment dismissal',()=>{assert.ok(!analyseContract('SERVICES AGREEMENT. Supplier may terminate without notice. Payment is due monthly.','service').issues.some(x=>x.id.startsWith('lra')));});
test('Protective first match does not hide an unsafe clause later',()=>{const r=analyseContract('Nothing excludes liability for personal injury. Clause 7: Supplier excludes liability for death or personal injury caused by negligence.','service','UK');assert.equal(r.issuesCount,1);assert.match(r.issues[0].excerpt,/Clause 7/);});
test('a monthly interest rate alone does not establish an NCA breach',()=>{const r=analyseContract('CREDIT AGREEMENT. Interest rate is 1 percent per month. An affordability assessment has been completed.','loan','ZA');assert.ok(!r.issues.some(x=>x.id.startsWith('nca')));});
test('sale title outranks incidental rental references',()=>{assert.match(analyseContract('SALE AGREEMENT. Buyer purchases the property from seller. An existing tenant occupies the premises under a lease.','property-sale.pdf','ZA').docType,/Sale Agreement/);});

test('paid decision brief includes prioritized action and confidence',()=>{const r=analyseContract('RESIDENTIAL LEASE. Rent R8000. The deposit is non-refundable. Landlord may enter the premises without notice.','lease.pdf','ZA');assert.match(r.decision,/Do not sign|Negotiate/);assert.ok(r.priorities.length>0);assert.ok(r.confidence);assert.notEqual(r.exposure,'Not estimated');});
test('surety is treated as a high-priority personal liability risk',()=>{const r=analyseContract('SERVICE AGREEMENT. The director binds himself as surety and co-principal debtor for all amounts on a continuing unlimited basis.','service.pdf','ZA');assert.ok(r.issues.some(x=>x.id.startsWith('surety-')));});
test('lease completeness flags missing inspection process',()=>{const r=analyseContract('RESIDENTIAL LEASE. Monthly rent R9000. Deposit will be held in an interest-bearing account.','lease.pdf','ZA');assert.ok(r.issues.some(x=>x.id.startsWith('missing-lease-inspection-')));});
